services:
  app:
    image: mcr.microsoft.com/devcontainers/python:1-3.12-bullseye
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    depends_on:
      - cosmosdb
    
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    environment:
      AZURE_COSMOS_EMULATOR_PARTITION_COUNT: 6
      AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE: "true"
    ports:
    - "8081:8081"
    volumes:
      - cosmosdb-data:/var/opt/data

volumes:
  cosmosdb-data: